import type { CockpitData } from "./types.ts";

export const defaultData: CockpitData = {
  maps: [
    {
      id: "components#81",
      repository: "salesai-internal/components",
      title: "Component library migration",
      destination:
        "A decision-complete migration plan with stable component boundaries, accessibility contracts, and an incremental adoption path.",
      notes: [
        "Preserve product delivery while migration proceeds.",
        "Public component contracts matter more than source parity.",
      ],
      fog: ["Visual regression ownership", "Package release cadence"],
      updated: "8m ago",
      state: "open",
      autoRun: true,
      outcome: "implemented",
      tickets: [
        {
          id: "#142",
          title: "Choose the accessibility contract",
          question:
            "Which accessibility behavior belongs in shared primitives, and which remains the consuming application's responsibility?",
          type: "research",
          mode: "AFK",
          domains: ["UI", "architecture"],
          capabilities: ["web", "code"],
          trackerState: "open",
          blockedBy: [],
        },
        {
          id: "#146",
          title: "Define error-presentation semantics",
          question:
            "Should components render domain errors, presentation errors, or only structured state supplied by consumers?",
          type: "grilling",
          mode: "HITL",
          domains: ["UI", "domain"],
          capabilities: [],
          trackerState: "open",
          blockedBy: [],
        },
        {
          id: "#151",
          title: "Prototype map navigation",
          question:
            "Which terminal interaction makes map state legible without turning the map into a project-management board?",
          type: "prototype",
          mode: "HITL",
          domains: ["UI"],
          capabilities: ["code"],
          trackerState: "claimed",
          assignee: "@jaren",
          blockedBy: [],
          agent: {
            runtime: "Pi",
            model: "inherited",
            effort: "high",
            state: "running",
          },
          workspace: {
            branch: "feat/wayfinder-cockpit",
            path: "../worktrees/wayfinder-cockpit",
            dirty: true,
          },
        },
        {
          id: "#156",
          title: "Implement tracker adapter contract",
          question:
            "What is the smallest capability-based interface that supports GitHub and local Markdown without encoding either system in the core?",
          type: "task",
          mode: "AFK",
          domains: ["architecture"],
          capabilities: ["code"],
          trackerState: "open",
          blockedBy: ["#142"],
        },
        {
          id: "#160",
          title: "Build repository settings surface",
          question:
            "How should global, repository, and map settings be visualized and overridden?",
          type: "task",
          mode: "HITL",
          domains: ["UI"],
          capabilities: ["code"],
          trackerState: "claimed",
          assignee: "@jaren",
          blockedBy: [],
          workspace: {
            branch: "feat/160-wayfinder-settings",
            path: "../worktrees/160-wayfinder-settings",
            dirty: false,
          },
          review: {
            number: 42,
            state: "review-required",
            checks: "passing",
          },
        },
        {
          id: "#163",
          title: "Survey component metadata formats",
          question:
            "Which existing metadata formats can represent portable ticket traits and adapter capabilities?",
          type: "research",
          mode: "AFK",
          domains: ["architecture", "web"],
          capabilities: ["web"],
          trackerState: "claimed",
          assignee: "wayfinder",
          blockedBy: [],
          agent: {
            runtime: "Codex",
            model: "GPT long-run",
            effort: "medium",
            state: "complete",
          },
          attention: "discovery",
        },
        {
          id: "#130",
          title: "Classify source components",
          question: "Which atomic-design category owns each source component?",
          type: "research",
          mode: "AFK",
          domains: ["UI"],
          capabilities: ["code"],
          trackerState: "resolved",
          blockedBy: [],
          agent: {
            runtime: "Claude",
            model: "Sonnet",
            effort: "high",
            state: "complete",
          },
        },
      ],
      activity: [
        "12:45  PR #42 requested review",
        "12:43  #163 proposed a prerequisite",
        "12:41  #163 research completed",
        "12:18  #151 started in a worktree",
        "11:52  #142 entered the frontier",
      ],
    },
    {
      id: "salesai#204",
      repository: "salesai-internal/salesai",
      title: "Conversation-state redesign",
      destination:
        "One explicit conversation-state model shared by ingestion, orchestration, and the operator UI.",
      notes: ["Do not migrate persistence until terminology stabilizes."],
      fog: ["Historical replay", "Cross-tenant analytics"],
      updated: "2h ago",
      state: "open",
      autoRun: false,
      outcome: "specification",
      tickets: [
        {
          id: "#211",
          title: "Name conversation lifecycle states",
          question: "Which lifecycle states exist and who owns each transition?",
          type: "grilling",
          mode: "HITL",
          domains: ["domain"],
          capabilities: [],
          trackerState: "open",
          blockedBy: [],
        },
        {
          id: "#214",
          title: "Audit persistence transitions",
          question: "Where are lifecycle transitions currently persisted?",
          type: "research",
          mode: "AFK",
          domains: ["data"],
          capabilities: ["code"],
          trackerState: "open",
          blockedBy: ["#211"],
        },
      ],
      activity: ["10:24  Map charted", "10:18  Destination updated"],
    },
    {
      id: "pi-config#33",
      repository: "JarenKempton/pi-config",
      title: "Safe agent orchestration",
      destination:
        "Predictable multi-runtime orchestration with explicit permissions, durable artifacts, and understandable cost controls.",
      notes: ["Restrictive profiles fail closed."],
      fog: ["Remote execution pools"],
      updated: "yesterday",
      state: "closed",
      autoRun: true,
      outcome: "implemented",
      tickets: [
        {
          id: "#34",
          title: "Define permission profiles",
          question: "Which capabilities belong to each execution profile?",
          type: "grilling",
          mode: "HITL",
          domains: ["security"],
          capabilities: [],
          trackerState: "resolved",
          blockedBy: [],
        },
        {
          id: "#35",
          title: "Verify runtime isolation",
          question: "Do all child runtimes enforce the selected profile?",
          type: "research",
          mode: "AFK",
          domains: ["security"],
          capabilities: ["code"],
          trackerState: "resolved",
          blockedBy: [],
        },
      ],
      activity: ["Yesterday  Map completed", "Yesterday  #35 resolved"],
    },
  ],
  discoveries: [
    {
      id: "discovery-1",
      mapId: "components#81",
      sourceTicketId: "#163",
      kind: "prerequisite",
      title: "Choose a portable ticket-traits encoding",
      rationale:
        "The adapter contract cannot preserve AFK mode and routing traits until their portable representation is decided.",
      suggestedType: "research",
      suggestedMode: "AFK",
      suggestedDomains: ["architecture"],
      suggestedCapabilities: ["web", "code"],
    },
    {
      id: "discovery-2",
      mapId: "components#81",
      sourceTicketId: "#163",
      kind: "fog",
      title: "Import metadata from external project boards",
      rationale:
        "Potentially useful, but outside the destination's tracker-adapter scope.",
      suggestedType: "research",
      suggestedMode: "AFK",
      suggestedDomains: ["integrations"],
      suggestedCapabilities: ["web"],
    },
  ],
  routes: [
    {
      id: "ui-research",
      name: "UI research",
      when: "research · AFK · domain:UI",
      runtime: "Claude",
      model: "sonnet",
      effort: "high",
      profile: "researcher",
      enabled: true,
    },
    {
      id: "long-web",
      name: "Long web collection",
      when: "AFK · capability:web · duration:long",
      runtime: "Codex",
      model: "gpt-5.6-sol",
      effort: "medium",
      profile: "researcher",
      enabled: true,
    },
    {
      id: "implementation",
      name: "AFK implementation",
      when: "task · AFK",
      runtime: "Pi",
      model: "inherit",
      effort: "high",
      profile: "worker",
      enabled: true,
    },
  ],
  agentCatalog: [
    {
      id: "Pi",
      source: "Pi model registry",
      models: [
        {
          id: "inherit",
          label: "Inherit current Pi model",
          efforts: ["off", "minimal", "low", "medium", "high", "xhigh", "max"],
          defaultEffort: "high",
        },
      ],
    },
    {
      id: "Claude",
      source: "Claude CLI aliases",
      models: [
        { id: "default", label: "Claude CLI default", efforts: ["low", "medium", "high", "xhigh", "max"], defaultEffort: "high" },
        { id: "sonnet", label: "Sonnet", efforts: ["low", "medium", "high", "xhigh", "max"], defaultEffort: "high" },
        { id: "opus", label: "Opus", efforts: ["low", "medium", "high", "xhigh", "max"], defaultEffort: "high" },
        { id: "fable", label: "Fable", efforts: ["low", "medium", "high", "xhigh", "max"], defaultEffort: "high" },
      ],
    },
    {
      id: "Codex",
      source: "Codex model cache",
      models: [
        { id: "gpt-5.6-sol", label: "GPT-5.6-Sol", efforts: ["low", "medium", "high", "xhigh", "max"], defaultEffort: "low" },
      ],
    },
  ],
  deliveryProfiles: [
    {
      id: "spec-handoff",
      label: "Specification handoff",
      outcome: "specification",
      approval: "Human accepts decision-complete specification",
      quality: ["Destination covered", "Fog separated", "Decisions linked"],
      integration: "Handoff only",
      release: "Not applicable",
      waitingLabel: "HANDOFF",
    },
    {
      id: "team-reviewed",
      label: "Team-reviewed implementation",
      outcome: "implemented",
      approval: "Peer review required",
      quality: ["Tests", "Typecheck", "Browser QA"],
      integration: "Branch + pull request",
      release: "After merge",
      waitingLabel: "REVIEW",
    },
    {
      id: "solo-guarded",
      label: "Solo guarded implementation",
      outcome: "implemented",
      approval: "Agent review + operator acceptance",
      quality: ["Tests", "Typecheck", "Second opinion"],
      integration: "Verified commit to main",
      release: "Manual push",
      waitingLabel: "QUALITY GATE",
    },
    {
      id: "direct-delivery",
      label: "Direct delivery",
      outcome: "deployed",
      approval: "Explicit ship confirmation",
      quality: ["Configured smoke tests"],
      integration: "Direct to main",
      release: "Automated after confirmation",
      waitingLabel: "READY TO SHIP",
    },
  ],
  trackers: [
    {
      id: "github",
      label: "GitHub Issues",
      repositoryLabel: "salesai-internal/components",
      instructions: "docs/agents/issue-tracker.md",
      auth: "gh CLI authenticated",
      capabilities: [
        { label: "Maps / child tickets", value: "native sub-issues", available: true },
        { label: "Dependencies", value: "native issue dependencies", available: true },
        { label: "Claiming", value: "assignee", available: true },
        { label: "Reviews", value: "GitHub pull requests", available: true },
      ],
    },
    {
      id: "gitlab",
      label: "GitLab Issues",
      repositoryLabel: "group/project",
      instructions: "docs/agents/issue-tracker.md",
      auth: "glab CLI required",
      capabilities: [
        { label: "Maps / child tickets", value: "related issues", available: true },
        { label: "Dependencies", value: "issue links", available: true },
        { label: "Claiming", value: "assignee", available: true },
        { label: "Reviews", value: "merge requests", available: true },
      ],
    },
    {
      id: "jira",
      label: "Jira",
      repositoryLabel: "site / project key",
      instructions: "docs/agents/issue-tracker.md",
      auth: "adapter not installed",
      capabilities: [
        { label: "Maps / child tickets", value: "issue hierarchy", available: true },
        { label: "Dependencies", value: "issue links", available: true },
        { label: "Claiming", value: "assignee", available: true },
        { label: "Reviews", value: "separate provider", available: false },
      ],
    },
    {
      id: "linear",
      label: "Linear",
      repositoryLabel: "workspace / team",
      instructions: "docs/agents/issue-tracker.md",
      auth: "adapter not installed",
      capabilities: [
        { label: "Maps / child tickets", value: "parent issues", available: true },
        { label: "Dependencies", value: "blocking relations", available: true },
        { label: "Claiming", value: "assignee", available: true },
        { label: "Reviews", value: "separate provider", available: false },
      ],
    },
    {
      id: "markdown",
      label: "Local Markdown",
      repositoryLabel: ".scratch/<effort>/",
      instructions: "docs/agents/issue-tracker.md",
      auth: "none",
      capabilities: [
        { label: "Maps / child tickets", value: "map + issue files", available: true },
        { label: "Dependencies", value: "Blocked by field", available: true },
        { label: "Claiming", value: "Status field", available: true },
        { label: "Reviews", value: "separate provider", available: false },
      ],
    },
    {
      id: "custom",
      label: "Custom adapter",
      repositoryLabel: "adapter-defined",
      instructions: "docs/agents/issue-tracker.md",
      auth: "adapter-defined",
      capabilities: [
        { label: "Maps / child tickets", value: "adapter capability", available: false },
        { label: "Dependencies", value: "adapter capability", available: false },
        { label: "Claiming", value: "adapter capability", available: false },
        { label: "Reviews", value: "adapter capability", available: false },
      ],
    },
  ],
};
